=== api-evangelist/amazon-health-dashboard/json-schema/health-entity-filter-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-health-dashboard/refs/heads/main/json-schema/health-entity-filter-schema.json",
  "title": "EntityFilter",
  "description": "The values to use to filter results from the <a href=\"https://docs.aws.amazon.com/health/latest/APIReference/API_DescribeAffectedEntities.html\">DescribeAffectedEntities</a> operation.",
  "type": "object",
  "properties": {
    "eventArns": {
      "allOf": [
        {
          "$ref": "#/components/schemas/eventArnList"
        },
        {
          "description": "A list of event ARNs (unique identifiers). For example: <code>\"arn:aws:health:us-east-1::event/EC2/EC2_INSTANCE_RETIREMENT_SCHEDULED/EC2_INSTANCE_RETIREMENT_SCHEDULED_ABC123-CDE456\", \"arn:aws:health:us-west-1::event/EBS/AWS_EBS_LOST_VOLUME/AWS_EBS_LOST_VOLUME_CHI789_JKL101\"</code> "
        }
      ]
    },
    "entityArns": {
      "allOf": [
        {
          "$ref": "#/components/schemas/entityArnList"
        },
        {
          "description": "A list of entity ARNs (unique identifiers)."
        }
      ]
    },
    "entityValues": {
      "allOf": [
        {
          "$ref": "#/components/schemas/entityValueList"
        },
        {
          "description": "A list of IDs for affected entities."
        }
      ]
    },
    "lastUpdatedTimes": {
      "allOf": [
        {
          "$ref": "#/components/schemas/dateTimeRangeList"
        },
        {
          "description": "A list of the most recent dates and times that the entity was updated."
        }
      ]
    },
    "tags": {
      "allOf": [
        {
          "$ref": "#/components/schemas/tagFilter"
        },
        {
          "description": "<p>A map of entity tags attached to the affected entity.</p> <note> <p>Currently, the <code>tags</code> property isn't supported.</p> </note>"
        }
      ]
    },
    "statusCodes": {
      "allOf": [
        {
          "$ref": "#/components/schemas/entityStatusCodeList"
        },
        {
          "description": "A list of entity status codes (<code>IMPAIRED</code>, <code>UNIMPAIRED</code>, or <code>UNKNOWN</code>)."
        }
      ]
    }
  },
  "required": [
    "eventArns"
  ]
}

=== api-evangelist/amazon-health-dashboard/examples/health-entity-filter-example.json
{
  "eventArns": "arn:aws:health:us-east-1::event/EC2/AWS_EC2_INSTANCE_ISSUE/abc123",
  "entityArns": "arn:aws:health:us-east-1::event/EC2/AWS_EC2_INSTANCE_ISSUE/abc123",
  "entityValues": "example-entityValues",
  "lastUpdatedTimes": "example-lastUpdatedT",
  "tags": "example-tags",
  "statusCodes": "open"
}
